---
fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib.git
    simplib: https://github.com/simp/pupmod-simp-simplib
    concat:  https://github.com/simp/puppetlabs-concat
  symlinks:
    incron: "#{source_dir}"
